version: '3.9'
x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: docker/Dockerfile.airflow
  environment:
    - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@postgres:5432/airflow
    - AIRFLOW__CORE__FERNET_KEY=FB0o_zt4e3Ziq3LdUUO7F2Z95cvFFx16hU8jTeR1ASM=
    - AIRFLOW__CELERY__BROKER_URL=pyamqp://guest:guest@broker:5672/
    - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql+psycopg2://postgres:postgres@postgres:5432/airflow
    - AIRFLOW__CORE__LOGGING_LEVEL=INFO
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=airflow
    - REDIS_PASSWORD=redispass
    - POSTGRES_PORT=5432
    - EXECUTOR=Celery
    - PYTHONPATH=/opt/airflow
  volumes:
    - ./dags:/opt/airflow/dags
    - ./airflow-data/includes:/opt/airflow/includes
    - ./airflow-data/logs:/opt/airflow/logs
    - ./airflow-data/plugins:/opt/airflow/plugins
    - ./airflow-data/airflow.cfg:/opt/airflow/airflow.cfg
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=airflow
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"

  redis:
    image: redis:5.0.5
    container_name: xcom_backends

  broker:
    image: rabbitmq:3.8-alpine
    container_name: broker

  airflow-init:
    << : *airflow-common
    container_name: airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - airflow users list || ( airflow db init &&
        airflow users create
          --role Admin
          --username airflow
          --password airflow
          --email airflow@airflow.com
          --firstname airflow
          --lastname airflow )
    restart: on-failure

  airflow-webserver:
    << : *airflow-common
    command: airflow webserver
    ports:
      - 8080:8080
    container_name: webserver
    restart: always
    depends_on:
      - airflow-init

  airflow-scheduler-1:
    << : *airflow-common
    command: airflow scheduler
    container_name: scheduler_1
    restart: always
    depends_on:
      - airflow-init

  airflow-scheduler-2:
    <<: *airflow-common
    container_name: scheduler_2
    command: >
      bash -c "(airflow upgradedb || airflow db upgrade) && airflow scheduler"
    restart: always
    depends_on:
      - airflow-init
      - airflow-scheduler-1

  worker:
    << : *airflow-common
    deploy:
      replicas: 2
    depends_on:
      - airflow-scheduler-1
      - airflow-scheduler-2
      - broker
    command: airflow celery worker
    restart: always

  flower:
    << : *airflow-common
    restart: always
    container_name: flower
    depends_on:
      - airflow-scheduler-1
      - airflow-scheduler-2
      - broker
    ports:
      - "5555:5555"
    command: airflow celery flower
